version: '3.8'
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: leeo
      POSTGRES_PASSWORD: default
      POSTGRES_DB: nestdb
    ports:
      - 5432:5432
